### ISSUE TITLE
Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by danieltrolezi** [mohithg/react-typeform#3]
Hi!

I can't get this to work.
Keep getting this error just for importing the module:

`Uncaught TypeError: Cannot read property 'element' of undefined`.

**app.js:**

```
class FormSubscribe extends React.Component {
  constructor(props) {
    super(props);
  }

  /**
   * Handles form submition
   */
  submit(event) {
    ...
  }

  render() {
    return (
      <TypeForm onSubmit={this.submit}>
        <Input type="text" label="Nome" name="name" required/>
      </TypeForm>
    )
  }
}
```

**component.js**

```
export class Input extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return(
      <div className="form-group">
        <label>{this.props.label} {this.props.required ? <span>*</span> : ''}</label>
        <input className="form-control" type={this.props.type} name={this.props.name} value={this.props.value} required={this.props.required}/>
      </div>
    )
  }
}
```

Where the prop `tfStyle` comes anyway?
If you can provided a full example it would be great!

Thanks!

**Comment by mohithg** [comment]
Thanks for using react-typeform. This is because react-typeform is not using React 16. Now I have updated to React16 in version 1.0.0.

I have created a working [demo](https://github.com/mohithg/react-typeform/wiki/Working-Example).

**Comment by mohithg** [comment]
Closing issue. Re-open it if you feel something is not right for you.
