### ISSUE TITLE
back button support?

### ISSUE THREAD

**Issue by futuremarc** [mohithg/react-typeform#5]
Hi,

Wondering if you'd consider supporting a native back button with all the support the next button has? It'd be really useful for these types of forms. I might have to fork and make one myself for now or create a PR sometime.

thanks!

**Comment by mohithg** [comment]
@futuremarc Thanks for asking, I can create one once I get some time. In the meanwhile, if you can get the feature ready in a PR, I am happy to merge this feature.

**Comment by mcclowes** [comment]
I've added this functionality, PR is here https://github.com/mohithg/react-typeform/pull/6

**Comment by mohithg** [comment]
Launched in 1.0.1. Thanks to @mcclowes for PR
